// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU9S1bfSzKmfSgz_KQ646JXkuda4z5nj4',
    appId: '1:1028525211416:web:e1542bfb944a057dada86d',
    messagingSenderId: '1028525211416',
    projectId: 'trufood-1aa1b',
    authDomain: 'trufood-1aa1b.firebaseapp.com',
    databaseURL: 'https://trufood-1aa1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trufood-1aa1b.appspot.com',
    measurementId: 'G-F4319VKML6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCC8BLDnelj6Xj9kjlqN7AdycydW4UiHc',
    appId: '1:1028525211416:android:f2b06cdbe98ec5ebada86d',
    messagingSenderId: '1028525211416',
    projectId: 'trufood-1aa1b',
    databaseURL: 'https://trufood-1aa1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trufood-1aa1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5yW8f-qst50n8OzYjhbgoQKcWJZ4uiVE',
    appId: '1:1028525211416:ios:9dcec16d032a2bdcada86d',
    messagingSenderId: '1028525211416',
    projectId: 'trufood-1aa1b',
    databaseURL: 'https://trufood-1aa1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trufood-1aa1b.appspot.com',
    iosBundleId: 'com.example.proto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5yW8f-qst50n8OzYjhbgoQKcWJZ4uiVE',
    appId: '1:1028525211416:ios:9dcec16d032a2bdcada86d',
    messagingSenderId: '1028525211416',
    projectId: 'trufood-1aa1b',
    databaseURL: 'https://trufood-1aa1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trufood-1aa1b.appspot.com',
    iosBundleId: 'com.example.proto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU9S1bfSzKmfSgz_KQ646JXkuda4z5nj4',
    appId: '1:1028525211416:web:becb1265a697fc83ada86d',
    messagingSenderId: '1028525211416',
    projectId: 'trufood-1aa1b',
    authDomain: 'trufood-1aa1b.firebaseapp.com',
    databaseURL: 'https://trufood-1aa1b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trufood-1aa1b.appspot.com',
    measurementId: 'G-3HGRT0TBW9',
  );
}
